export const mockDesigns = [
  {
    id: "1",
    name: "Elegant Evening Gown",
    image: "/elegant-african-ankara-evening-gown.jpg",
    fabric: "Premium Ankara Wax Print",
    occasion: "Formal Events",
    bodyType: "Hourglass",
    price: "KES 25,000",
    description: "Stunning floor-length gown with intricate Ankara patterns",
  },
  {
    id: "2",
    name: "Modern Jumpsuit",
    image: "/modern-african-ankara-jumpsuit.jpg",
    fabric: "Cotton Ankara",
    occasion: "Casual Outings",
    bodyType: "Rectangle",
    price: "KES 18,000",
    description: "Contemporary jumpsuit perfect for everyday elegance",
  },
  {
    id: "3",
    name: "Traditional Wrapper Set",
    image: "/traditional-african-ankara-wrapper-set.jpg",
    fabric: "Silk Ankara Blend",
    occasion: "Cultural Events",
    bodyType: "Pear",
    price: "KES 20,000",
    description: "Classic wrapper and blouse combination",
  },
  {
    id: "4",
    name: "Office Blazer",
    image: "/professional-african-ankara-blazer.jpg",
    fabric: "Structured Ankara",
    occasion: "Professional",
    bodyType: "Inverted Triangle",
    price: "KES 22,000",
    description: "Professional blazer with subtle Ankara accents",
  },
  {
    id: "5",
    name: "Cocktail Dress",
    image: "/african-ankara-cocktail-dress.jpg",
    fabric: "Premium Ankara",
    occasion: "Evening Events",
    bodyType: "Hourglass",
    price: "KES 19,500",
    description: "Chic cocktail dress with bold Ankara prints",
  },
  {
    id: "6",
    name: "Maxi Skirt Set",
    image: "/african-ankara-maxi-skirt.jpg",
    fabric: "Cotton Ankara",
    occasion: "Casual",
    bodyType: "Pear",
    price: "KES 15,000",
    description: "Flowing maxi skirt with matching crop top",
  },
]

export const mockTailors = [
  {
    id: "1",
    name: "Wanjiku Kamau",
    avatar: "/kenyan-woman-fashion-designer.jpg",
    rating: 4.9,
    reviews: 127,
    location: "Nairobi, Kenya",
    specialties: ["Evening Wear", "Traditional Attire"],
    yearsExperience: 8,
    completedOrders: 450,
    priceRange: "KES 15,000 - 30,000",
  },
  {
    id: "2",
    name: "Omondi Otieno",
    avatar: "/kenyan-man-fashion-designer.jpg",
    rating: 4.8,
    reviews: 98,
    location: "Mombasa, Kenya",
    specialties: ["Modern Fusion", "Casual Wear"],
    yearsExperience: 6,
    completedOrders: 320,
    priceRange: "KES 12,000 - 25,000",
  },
  {
    id: "3",
    name: "Akinyi Odhiambo",
    avatar: "/kenyan-woman-tailor.jpg",
    rating: 5.0,
    reviews: 156,
    location: "Kisumu, Kenya",
    specialties: ["Bridal", "Formal Events"],
    yearsExperience: 10,
    completedOrders: 580,
    priceRange: "KES 20,000 - 40,000",
  },
  {
    id: "4",
    name: "Njeri Mwangi",
    avatar: "/kenyan-woman-fashion-designer-smiling.jpg",
    rating: 4.9,
    reviews: 143,
    location: "Nakuru, Kenya",
    specialties: ["Corporate Wear", "Casual Designs"],
    yearsExperience: 7,
    completedOrders: 390,
    priceRange: "KES 10,000 - 22,000",
  },
]

export const mockOrders = [
  {
    id: "ORD-001",
    design: "Elegant Evening Gown",
    tailor: "Wanjiku Kamau",
    status: "In Progress",
    date: "2024-01-15",
    amount: "KES 25,000",
    timeline: [
      { step: "Order Placed", completed: true, date: "Jan 15" },
      { step: "Measurements Confirmed", completed: true, date: "Jan 16" },
      { step: "Fabric Selected", completed: true, date: "Jan 17" },
      { step: "In Production", completed: false, date: "Jan 20" },
      { step: "Quality Check", completed: false, date: "Jan 25" },
      { step: "Delivered", completed: false, date: "Jan 28" },
    ],
  },
  {
    id: "ORD-002",
    design: "Modern Jumpsuit",
    tailor: "Omondi Otieno",
    status: "Delivered",
    date: "2024-01-10",
    amount: "KES 18,000",
    timeline: [
      { step: "Order Placed", completed: true, date: "Jan 10" },
      { step: "Measurements Confirmed", completed: true, date: "Jan 11" },
      { step: "Fabric Selected", completed: true, date: "Jan 12" },
      { step: "In Production", completed: true, date: "Jan 15" },
      { step: "Quality Check", completed: true, date: "Jan 18" },
      { step: "Delivered", completed: true, date: "Jan 20" },
    ],
  },
  {
    id: "ORD-003",
    design: "Office Blazer",
    tailor: "Njeri Mwangi",
    status: "Pending",
    date: "2024-01-20",
    amount: "KES 22,000",
    timeline: [
      { step: "Order Placed", completed: true, date: "Jan 20" },
      { step: "Measurements Confirmed", completed: false, date: "Jan 21" },
      { step: "Fabric Selected", completed: false, date: "Jan 22" },
      { step: "In Production", completed: false, date: "Jan 25" },
      { step: "Quality Check", completed: false, date: "Jan 28" },
      { step: "Delivered", completed: false, date: "Jan 30" },
    ],
  },
]

export const mockUsers = [
  {
    id: "1",
    name: "Wanjiru Kariuki",
    email: "wanjiru.k@example.com",
    role: "client",
    joinDate: "2023-11-15",
    orders: 5,
    totalSpent: "KES 95,000",
  },
  {
    id: "2",
    name: "Kamau Maina",
    email: "kamau.m@example.com",
    role: "client",
    joinDate: "2023-12-01",
    orders: 3,
    totalSpent: "KES 58,000",
  },
  {
    id: "3",
    name: "Achieng Onyango",
    email: "achieng.o@example.com",
    role: "client",
    joinDate: "2024-01-05",
    orders: 2,
    totalSpent: "KES 42,000",
  },
]
